### ISSUE TITLE
googleapiclient.errors.HttpError

### ISSUE THREAD

**Issue by eapo** [koyan/rocketchat-google-calendar#4]
> Fire up the OAuth authentication process by running it once on shell/terminal

was the most complicated process for me on Debian server, without luck:

```
# python calendarWebhook.py
Traceback (most recent call last):
  File "calendarWebhook.py", line 116, in <module>
    main()
  File "calendarWebhook.py", line 81, in main
    calendarId=calendarId).execute()
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/d2V...?alt=json returned "Not Found">
```

**Comment by koyan** [comment]
Hi there,
Can you try google's own tutorial: 
https://developers.google.com/calendar/quickstart/python
And see if it works?

**Comment by eapo** [comment]
```
python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 29, in <module>
    creds = store.get()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

```

:(

**Comment by koyan** [comment]
This is how much my help can reach. I am no Debian expert, and if the Google's tutorial does not work, then the rocketchat script will probably not work either (Since it is based on the google tutorial). 
Sorry.
